spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
          ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/microservices1
    username: root
    password:
  config:
    import: "optional:configserver:"
  application:
    name: FACULTY-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/




server:
  port: 9001

